import type { CapabilityDefinition } from '../../domain/capability.js';

export const foundationCapabilities: readonly CapabilityDefinition[] = [
  {
    id: 'foundation.action_planning',
    domain: 'foundation',
    title: 'EVE action planning',
    description: 'Validate and persist an exact short-lived plan for a locally enabled EVE action.',
    semantic_tools: ['prepare_eve_action'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'character',
    operation_class: 'action',
    sources: ['local'],
    pagination: { mode: 'none' },
    freshness: { mode: 'uncached' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'foundation.action_execution',
    domain: 'foundation',
    title: 'Confirmed EVE action execution',
    description: 'Execute one confirmed, unexpired, single-use EVE action plan and record a sanitized audit event.',
    semantic_tools: ['execute_eve_action'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'character',
    operation_class: 'action',
    sources: ['local'],
    pagination: { mode: 'none' },
    freshness: { mode: 'uncached' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'foundation.operation_discovery',
    domain: 'foundation',
    title: 'Complete ESI operation discovery',
    description: 'Search the reviewed ESI catalog and retrieve operation-specific input contracts.',
    semantic_tools: ['find_eve_capabilities'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'read',
    sources: ['local'],
    pagination: { mode: 'none' },
    freshness: { mode: 'static' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'foundation.bounded_esi_reads',
    domain: 'foundation',
    title: 'Bounded ESI read execution',
    description: 'Execute a registered, strictly validated read-only ESI capability without accepting raw network controls.',
    semantic_tools: ['execute_eve_read'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'read',
    sources: ['local'],
    pagination: { mode: 'page', default_limit: 1, maximum_limit: 5 },
    freshness: { mode: 'source_headers' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'foundation.capability_discovery',
    domain: 'foundation',
    title: 'EVE capability discovery',
    description: 'Discover available, degraded, disabled, and planned EVE Copilot capabilities.',
    semantic_tools: ['get_eve_capabilities'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'read',
    sources: ['local'],
    pagination: { mode: 'cursor', default_limit: 100, maximum_limit: 200 },
    freshness: { mode: 'static' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'foundation.server_diagnostics',
    domain: 'foundation',
    title: 'Server diagnostics',
    description: 'Inspect safe local readiness and configuration diagnostics.',
    semantic_tools: ['get_server_diagnostics'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'read',
    sources: ['local'],
    pagination: { mode: 'none' },
    freshness: { mode: 'uncached' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'foundation.server_status',
    domain: 'foundation',
    title: 'Server status',
    description: 'Return a compact EVE Copilot MCP readiness summary.',
    semantic_tools: ['get_server_status'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'read',
    sources: ['local'],
    pagination: { mode: 'none' },
    freshness: { mode: 'uncached' },
    implementation: 'available',
    attribution_refs: [],
  },
];
