import type { CapabilityDefinition } from '../../domain/capability.js';

export const guideCapabilities: readonly CapabilityDefinition[] = [
  {
    id: 'guide.search',
    domain: 'guide',
    title: 'Search the user-specific EVE guide',
    description: 'Search private advisory synthesis from earlier EVE questions without treating it as current or authoritative data.',
    semantic_tools: ['search_eve_guide'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'read',
    sources: ['user_guide'],
    pagination: { mode: 'none' },
    freshness: { mode: 'uncached' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'guide.read',
    domain: 'guide',
    title: 'Read a user-specific EVE guide page',
    description: 'Read one advisory guide page or historical revision with provenance and freshness assessment.',
    semantic_tools: ['read_eve_guide_page'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'read',
    sources: ['user_guide'],
    pagination: { mode: 'none' },
    freshness: { mode: 'uncached' },
    implementation: 'available',
    attribution_refs: [],
  },
  {
    id: 'guide.maintain',
    domain: 'guide',
    title: 'Maintain the user-specific EVE guide',
    description: 'Safely create, revise, supersede, archive, invalidate, remove, and restore advisory guide pages.',
    semantic_tools: ['maintain_eve_guide'],
    esi_operations: [],
    required_scopes: [],
    required_roles: [],
    access: 'public',
    operation_class: 'local_mutation',
    sources: ['user_guide'],
    pagination: { mode: 'none' },
    freshness: { mode: 'uncached' },
    implementation: 'available',
    attribution_refs: [],
  },
];
