import type { AnalyzeFittingChanges } from './analyze-fitting-changes.js';
import type { CancelCharacterConnection } from './cancel-character-connection.js';
import type { ConnectCharacter } from './connect-character.js';
import type { DisconnectCharacter } from './disconnect-character.js';
import type { ExecuteBoundedRead } from './execute-bounded-read.js';
import type { ExecuteEveAction } from './execute-eve-action.js';
import type { ExecuteSemanticRead } from './execute-semantic-read.js';
import type { FindEveCapabilities } from './find-eve-capabilities.js';
import type { GetCharacterConnectionStatus } from './get-character-connection-status.js';
import type { GetCharacterOverview } from './get-character-overview.js';
import type { GetCurrentLocation } from './get-current-location.js';
import type { GetCurrentShip } from './get-current-ship.js';
import type { GetEveCapabilities } from './get-eve-capabilities.js';
import type { GetEveCopilotProfile } from './get-eve-copilot-profile.js';
import type { GetServerDiagnostics } from './get-server-diagnostics.js';
import type { GetServerStatus } from './get-server-status.js';
import type { ListCharacters } from './list-characters.js';
import type { MaintainEveGuide } from './maintain-eve-guide.js';
import type { PrepareEveAction } from './prepare-eve-action.js';
import type { ReadEveGuidePage } from './read-eve-guide-page.js';
import type { ReauthorizeCharacter } from './reauthorize-character.js';
import type { SearchEveGuide } from './search-eve-guide.js';
import type { SelectCharacter } from './select-character.js';

export interface AppServices {
  readonly getEveCopilotProfile: GetEveCopilotProfile;
  readonly getEveCapabilities: GetEveCapabilities;
  readonly getServerDiagnostics: GetServerDiagnostics;
  readonly getServerStatus: GetServerStatus;
  readonly connectCharacter: ConnectCharacter;
  readonly getCharacterConnectionStatus: GetCharacterConnectionStatus;
  readonly cancelCharacterConnection: CancelCharacterConnection;
  readonly reauthorizeCharacter: ReauthorizeCharacter;
  readonly listCharacters: ListCharacters;
  readonly selectCharacter: SelectCharacter;
  readonly disconnectCharacter: DisconnectCharacter;
  readonly getCharacterOverview: GetCharacterOverview;
  readonly getCurrentLocation: GetCurrentLocation;
  readonly getCurrentShip: GetCurrentShip;
  readonly executeBoundedRead: ExecuteBoundedRead;
  readonly findEveCapabilities: FindEveCapabilities;
  readonly prepareEveAction: PrepareEveAction;
  readonly executeEveAction: ExecuteEveAction;
  readonly executeSemanticRead: ExecuteSemanticRead;
  readonly analyzeFittingChanges: AnalyzeFittingChanges;
  readonly searchEveGuide: SearchEveGuide;
  readonly readEveGuidePage: ReadEveGuidePage;
  readonly maintainEveGuide: MaintainEveGuide;
}
